=== biolds/unraid_templates/template_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Container">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Repository" type="xs:string"/>
                <xs:element name="Registry" type="xs:string"/>
                <xs:element name="Branch" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tag" type="xs:string"/>
                            <xs:element name="TagDescription" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Network" type="xs:string"/>
                <xs:element name="WebUI" type="xs:string"/>
                <xs:element name="Privileged" type="xs:boolean"/>
                <xs:element name="Support" type="xs:string"/>
                <xs:element name="Project" type="xs:string"/>
                <xs:element name="Overview" type="xs:string"/>
                <xs:element name="Beta" type="xs:string"/>
                <xs:element name="Category" type="xs:string"/>
                <xs:element name="ExtraSearchTerms" type="xs:string"/>
                <xs:element name="Icon" type="xs:string"/>
                <xs:element name="TemplateURL" type="xs:string"/>
                <xs:element name="Screenshot" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="Maintainer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="WebPage" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Changes" type="xs:string"/>
                <xs:element name="Config" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="Name" type="xs:string" use="required"/>
                                <xs:attribute name="Target" type="xs:string" use="required"/>
                                <xs:attribute name="Default" type="xs:string" use="required"/>
                                <xs:attribute name="Mode" type="xs:string"/>
                                <xs:attribute name="Description" type="xs:string" use="required"/>
                                <xs:attribute name="Type" type="xs:string" use="required"/>
                                <xs:attribute name="Display" type="xs:string" use="required"/>
                                <xs:attribute name="Required" type="xs:boolean" use="required"/>
                                <xs:attribute name="Mask" type="xs:boolean" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== biolds/unraid_templates/templates/wedding_share.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>WeddingShare</Name>
    <Repository>cirx08/wedding_share:latest</Repository>
    <Registry>https://hub.docker.com/r/cirx08/wedding_share</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:5000]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/cirx08/WeddingShare/issues</Support>
    <Project>https://github.com/cirx08/WeddingShare</Project>
    <Overview>
        A basic photo sharing site, allowing anyone to upload and view shared albums.
    </Overview>
    <Beta>False</Beta>
    <Category>MediaApp:Photos MediaServer:Photos Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>photo album share image gallery pictures wedding event party</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/wedding-share-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/wedding_share.xml</TemplateURL>
    <Screenshot>https://raw.githubusercontent.com/Cirx08/WeddingShare/main/screenshots/Homepage.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/Cirx08/WeddingShare/main/screenshots/Gallery.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/Cirx08/WeddingShare/main/screenshots/Homepage-Mobile.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/Cirx08/WeddingShare/main/screenshots/Gallery-Mobile.png</Screenshot>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2024-11-19

        Initial release
    </Changes>
    <Config Name="Web UI Port" Target="5000" Default="5000" Mode="tcp" Description="Container Port: 5000" Type="Port" Display="always-hide" Required="true" Mask="false">5000</Config>
    <Config Name="App Title" Target="TITLE" Default="Wedding Share" Description="Title of the app" Type="Variable" Display="always-hide" Required="true" Mask="false">Wedding Share</Config>
    <Config Name="Logo URL" Target="LOGO" Default="https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/wedding-share-icon.png" Description="URL of the logo" Type="Variable" Display="always-hide" Required="true" Mask="false">https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/wedding-share-icon.png</Config>
    <Config Name="Gallery Column Count" Target="GALLERY_COLUMNS" Default="4" Description="Number of columns in the gallery" Type="Variable" Display="always-hide" Required="true" Mask="false">4</Config>
    <Config Name="Allowed File Types" Target="ALLOWED_FILE_TYPES" Default=".jpg,.jpeg,.png" Description="Comma separated list of allowed file types" Type="Variable" Display="always-hide" Required="true" Mask="false">.jpg,.jpeg,.png</Config>
    <Config Name="Max File Size" Target="MAX_FILE_SIZE_MB" Default="10" Description="Maximum file size in MB" Type="Variable" Display="always-hide" Required="true" Mask="false">10</Config>
    <Config Name="Secret Key" Target="SECRET_KEY" Default="" Description="Secret key to combat strangers uploading. Optional, but recommended." Type="Variable" Display="always" Required="false" Mask="true"/>
    <Config Name="Disable Upload" Target="DISABLE_UPLOAD" Default="false|true" Description="Disable the ability to upload files" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Disable QR Code" Target="DISABLE_QR_CODE" Default="false|true" Description="Disable the sharable QR code" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Hide Secret Key from QR Code" Target="HIDE_KEY_FROM_QR_CODE" Default="false|true" Description="Hide the secret key from the QR code" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Disable Home Link" Target="DISABLE_HOME_LINK" Default="false|true" Description="Disable the home link" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Uploads path" Target="/app/wwwroot/uploads" Default="/mnt/user/appdata/wedding_share/uploads" Description="Path to uploaded files" Type="Path" Display="always-hide" Required="true" Mask="false">/mnt/user/appdata/wedding_share/uploads</Config>
</Container>

=== biolds/unraid_templates/templates/huntarr.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>Huntarr</Name>
    <Repository>huntarr/huntarr:latest</Repository>
    <Registry>https://hub.docker.com/r/huntarr/huntarr</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:9705]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/plexguide/Huntarr.io/issues</Support>
    <Project>https://huntarr.io</Project>
    <Overview>
        A specialized utility that automates discovering missing and upgrading your media collection!
    </Overview>
    <Beta>False</Beta>
    <Category>Downloaders: MediaApp:Video MediaServer:Video Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>sonarr radarr lidarr readarr whisparr huntarr media tv show movies music audio video books files anime search indexer torrent usenet plex jellyfin emby content upgrade profile quality download missing arrs</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/plexguide/Huntarr.io/main/frontend/static/logo/512.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/huntarr.xml</TemplateURL>
    <Screenshot>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/huntarr_demo_1.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/huntarr_demo_2.png</Screenshot>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2024-04-24

        Initial release
    </Changes>
    <Config Name="Web UI Port" Target="9705" Default="9705" Mode="tcp" Description="Container Port: 9705" Type="Port" Display="always-hide" Required="true" Mask="false">9705</Config>
    <Config Name="Config Path" Target="/config" Default="/mnt/user/appdata/huntarr/config" Description="Path to config files" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/huntarr/config</Config>
</Container>
